package view;

import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import java.text.DecimalFormat;

public class InputTransaksi extends javax.swing.JPanel {
    private DecimalFormat currencyFormatter = new DecimalFormat("#,##0.00");
    
    public InputTransaksi() {
        initComponents();
        InputTotal.setEditable(false);
        setupAutoCalculation();
        setupButtonListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelInputTransaksi = new javax.swing.JLabel();
        LabelKode = new javax.swing.JLabel();
        LabelNama = new javax.swing.JLabel();
        LabelHarga = new javax.swing.JLabel();
        LabelJumlah = new javax.swing.JLabel();
        LabelTotal = new javax.swing.JLabel();
        btnHome = new javax.swing.JButton();
        InputKode = new javax.swing.JTextField();
        InputNama = new javax.swing.JTextField();
        InputHarga = new javax.swing.JTextField();
        InputJumlah = new javax.swing.JTextField();
        InputTotal = new javax.swing.JTextField();
        btnLihatTransaksi = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TabelBarang = new javax.swing.JTable();

        LabelInputTransaksi.setText("INPUT TRANSAKSI");

        LabelKode.setText("KODE");

        LabelNama.setText("NAMA");

        LabelHarga.setText("HARGA");

        LabelJumlah.setText("JUMLAH");

        LabelTotal.setText("TOTAL");

        btnHome.setText("HOME");

        InputKode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InputKodeActionPerformed(evt);
            }
        });

        btnLihatTransaksi.setText("LIHAT TRANSAKSI");

        btnSimpan.setText("SIMPAN");

        TabelBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "KODE", "NAMA", "HARGA", "STOK", "KATEGORI"
            }
        ));
        jScrollPane3.setViewportView(TabelBarang);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelHarga, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelNama, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelKode, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelInputTransaksi)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnHome)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(InputKode)
                                    .addComponent(InputNama)
                                    .addComponent(InputHarga)
                                    .addComponent(InputJumlah)
                                    .addComponent(InputTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLihatTransaksi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(LabelInputTransaksi)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelKode)
                    .addComponent(InputKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNama)
                    .addComponent(InputNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelHarga)
                    .addComponent(InputHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelJumlah)
                    .addComponent(InputJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTotal)
                    .addComponent(InputTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLihatTransaksi)
                    .addComponent(btnSimpan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnHome)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void setupAutoCalculation() {
        DocumentListener calculationListener = new DocumentListener() {
            public void changedUpdate(DocumentEvent e) {
                calculateTotal();
            }
            public void removeUpdate(DocumentEvent e) {
                calculateTotal();
            }
            public void insertUpdate(DocumentEvent e) {
                calculateTotal();
            }
        };
            InputHarga.getDocument().addDocumentListener(calculationListener);
            InputJumlah.getDocument().addDocumentListener(calculationListener);
    }
    
    private void calculateTotal() {
        double harga = 0.0;
        int jumlah = 0;

        try {
            String hargaText = InputHarga.getText().trim();
            if (!hargaText.isEmpty()) {
                harga = Double.parseDouble(hargaText);
            }

            String jumlahText = InputJumlah.getText().trim();
            if (!jumlahText.isEmpty()) {
                jumlah = Integer.parseInt(jumlahText);
            }

            double total = harga * jumlah;

            InputTotal.setText(currencyFormatter.format(total));
        } catch (NumberFormatException ex) {
            InputTotal.setText("INVALID INPUT");
            JOptionPane.showMessageDialog(this, "Harga atau Jumlah harus angka!", "Input Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void setupButtonListeners() {
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnLihatTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLihatTransaksiActionPerformed(evt);
            }
        });
    }
    
     private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {                                        
        HomePanel home = new HomePanel(); // Create a new HomePanel frame
        home.setVisible(true); // Make it visible
        this.dispose(); 
    }         
     
     private void btnLihatTransaksiActionPerformed(java.awt.event.ActionEvent evt) {                                                  
        LihatTransaksi lihatTransaksi = new LihatTransaksi(); 
        lihatTransaksi.setVisible(true); 
        this.dispose(); 
     }
     
     
     
    private void InputKodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InputKodeActionPerformed

    }//GEN-LAST:event_InputKodeActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField InputHarga;
    private javax.swing.JTextField InputJumlah;
    private javax.swing.JTextField InputKode;
    private javax.swing.JTextField InputNama;
    private javax.swing.JTextField InputTotal;
    private javax.swing.JLabel LabelHarga;
    private javax.swing.JLabel LabelInputTransaksi;
    private javax.swing.JLabel LabelJumlah;
    private javax.swing.JLabel LabelKode;
    private javax.swing.JLabel LabelNama;
    private javax.swing.JLabel LabelTotal;
    private javax.swing.JTable TabelBarang;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnLihatTransaksi;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    private void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
